"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateProductController = exports.deleteProductController = exports.getByIdProductController = exports.getAllProductController = exports.createProductController = exports.updateProductUseCase = exports.deleteProductUseCase = exports.getByIdProductUseCase = exports.getAllUseCase = exports.createProductUseCase = exports.productRepository = void 0;
const CreateBoletoUseCase_1 = require("../../../application/CreateBoletoUseCase");
const GetAllBoletoUseCase_1 = require("../../../application/GetAllBoletoUseCase");
const GetByIdBoletoUseCase_1 = require("../../../application/GetByIdBoletoUseCase");
const CreateBoletoController_1 = require("../controllers/CreateBoletoController");
const GetAllBoletoController_1 = require("../controllers/GetAllBoletoController");
const GetByIdBoletoController_1 = require("../controllers/GetByIdBoletoController");
const MysqlBoletoRepository_1 = require("../../adapters/MysqlBoletoRepository");
const DeleteBoletoController_1 = require("../controllers/DeleteBoletoController");
const DeleteBoletoUseCase_1 = require("../../../application/DeleteBoletoUseCase");
const UpdateBoletoController_1 = require("../controllers/UpdateBoletoController");
const UpdateBoletoUseCase_1 = require("../../../application/UpdateBoletoUseCase");
exports.productRepository = new MysqlBoletoRepository_1.MysqlProductRepository();
exports.createProductUseCase = new CreateBoletoUseCase_1.CreateProductUseCase(exports.productRepository);
exports.getAllUseCase = new GetAllBoletoUseCase_1.GetAllProductUseCase(exports.productRepository);
exports.getByIdProductUseCase = new GetByIdBoletoUseCase_1.GetByIdProductUseCase(exports.productRepository);
exports.deleteProductUseCase = new DeleteBoletoUseCase_1.DeleteProductUseCase(exports.productRepository);
exports.updateProductUseCase = new UpdateBoletoUseCase_1.UpdateProductUseCase(exports.productRepository);
exports.createProductController = new CreateBoletoController_1.CreateProductController(exports.createProductUseCase);
exports.getAllProductController = new GetAllBoletoController_1.GetAllProductController(exports.getAllUseCase);
exports.getByIdProductController = new GetByIdBoletoController_1.GetByIdProductController(exports.getByIdProductUseCase);
exports.deleteProductController = new DeleteBoletoController_1.DeleteProductController(exports.deleteProductUseCase);
exports.updateProductController = new UpdateBoletoController_1.UpdateProductController(exports.updateProductUseCase);
